version: '3'

services:
  psql:
    image: postgres
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=edelweiss

  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=pgadmin4@pgadmin.org
      - DEFAULT_PASSWORD=admin

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123