# based off minikube registry addon https://github.com/kubernetes/minikube/tree/master/deploy/addons/registry
# addon not used to avoid dependency on minikube.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: registry
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: registry
    spec:
      containers:
      - image: registry:2.6.1
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: registry
  name: registry
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: registry